/* Mock data for hubs, colleges and events */
window.APP = window.APP || {};
APP.data = {
  hubs: [
    {
      id: "data-science",
      name: "Data Science",
      desc: "Data analysis, machine learning and data engineering groups.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "ds-1",
          title: "Python Basics for Data Science",
          url: "https://www.youtube.com/watch?v=UrsmFxEIp5k&pp=ygUScHl0aG9uIGZ1bGwgY291cnNl",
        },
        {
          id: "ds-2",
          title: "Data Analysis with Pandas",
          url: "https://www.youtube.com/watch?v=_v41Yf2EQkU",
        },
        {
          id: "ds-3",
          title: "Machine Learning Fundamentals",
          url: "https://www.youtube.com/watch?v=k3jnGiR25O0",
        },
      ],
    },
    {
      id: "ai-ml",
      name: "AI & ML",
      desc: "Artificial intelligence and machine learning clubs.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "ai-1",
          title: "Python Crash Course",
          url: "https://www.youtube.com/watch?v=UrsmFxEIp5k&pp=ygUScHl0aG9uIGZ1bGwgY291cnNl",
        },
        {
          id: "ai-2",
          title: "Deep Learning Tutorial",
          url: "https://www.youtube.com/watch?v=UYW3PH3YzKQ",
        },
        {
          id: "ai-3",
          title: "Neural Networks Explained",
          url: "https://www.youtube.com/watch?v=viZrOnJclWc",
        },
      ],
    },
    {
      id: "civil-engineering",
      name: "Civil Engineering",
      desc: "Civil engineering societies and project teams.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "ce-1",
          title: "Civil Engineering Basics",
          url: "https://www.youtube.com/watch?v=XE-hhVMNI-o",
        },
        {
          id: "ce-2",
          title: "Structural Design Tutorial",
          url: "https://www.youtube.com/watch?v=QLb0zTLMLSI",
        },
      ],
    },
    {
      id: "mechanical-engineering",
      name: "Mechanical Engineering",
      desc: "Mechanical systems, design and robotics groups.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "me-1",
          title: "Mechanical Engineering 101",
          url: "https://www.youtube.com/watch?v=v21-j9Rqcg4",
        },
        {
          id: "me-2",
          title: "Thermodynamics Course",
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        },
        {
          id: "me-3",
          title: "Robotics Fundamentals",
          url: "https://www.youtube.com/watch?v=fwq8HXNj3eg",
        },
      ],
    },
    {
      id: "web-development",
      name: "Web Development",
      desc: "Frontend and backend web developer communities.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "web-1",
          title: "Frontend Course",
          url: "https://www.youtube.com/watch?v=G3e-cpL7ofc&t=14044s",
        },
        {
          id: "web-2",
          title: "React.js Tutorial",
          url: "https://www.youtube.com/watch?v=jBzwzrDvZ18",
        },
        {
          id: "web-3",
          title: "Full Stack Web Development",
          url: "https://www.youtube.com/watch?v=3wFpeDW0XP4",
        },
      ],
    },
    {
      id: "cybersecurity",
      name: "Cybersecurity",
      desc: "Information security clubs, CTFs and research.",
      icon: "js/icons/hub.svg",
      lectures: [
        {
          id: "cyber-1",
          title: "Cyber Security Crash Course",
          url: "https://www.youtube.com/watch?v=9HOpanT0GRs&pp=ygUVY3liZXIgc2VjdXJpdHkgY291cnNl",
        },
        {
          id: "cyber-2",
          title: "Ethical Hacking Fundamentals",
          url: "https://www.youtube.com/watch?v=66Xp-drtL9s",
        },
        {
          id: "cyber-3",
          title: "Network Security Tutorial",
          url: "https://www.youtube.com/watch?v=Ll5hNOI7D3E",
        },
      ],
    },
  ],
  colleges: [
    {
      id: "apsit",
      name: "AP Shah Institute of Technology",
      shortName: "APSIT",
      hub: "web-development",
      location: "Thane, Mumbai",
      img: "js/icons/college.svg",
      description: "Premier engineering institute focused on technology and innovation. Known for strong CS and IT programs with industry partnerships.",
      studentCount: "2500+",
      founded: "2004",
      website: "https://www.apsit.edu.in",
    },
    {
      id: "iitb",
      name: "Indian Institute of Technology Bombay",
      shortName: "IIT Bombay",
      hub: "ai-ml",
      location: "Mumbai",
      img: "js/icons/college.svg",
      description: "Top-tier national institute of engineering and technology. Excellence in research, innovation, and industry collaboration.",
      studentCount: "10000+",
      founded: "1958",
      website: "https://www.iitb.ac.in",
    },
    {
      id: "nmims",
      name: "NMIMS University",
      shortName: "NMIMS",
      hub: "data-science",
      location: "Mumbai",
      img: "js/icons/college.svg",
      description: "Prestigious private university with strong programs in engineering, management, and data science. Focus on skill development and placements.",
      studentCount: "15000+",
      founded: "1981",
      website: "https://www.nmims.edu",
    },
  ],
  events: [
    {
      id: 1,
      college: "AP Shah Institute of Technology",
      title: "Antarang - Annual Tech & Cultural Fest",
      date: "2026-03-21",
      time: "10:00",
      location: "APSIT Campus",
      desc: "APSIT's flagship annual fest featuring tech competitions, cultural events, and performances.",
    },
    {
      id: 2,
      college: "AP Shah Institute of Technology",
      title: "CodeSprint Hackathon",
      date: "2026-01-19",
      time: "09:00",
      location: "Innovation Lab, APSIT",
      desc: "24-hour coding marathon for APSIT students. Build innovative solutions and win prizes.",
    },
    {
      id: 3,
      college: "AP Shah Institute of Technology",
      title: "Web Development Workshop",
      date: "2026-02-05",
      time: "15:30",
      location: "Computer Lab 3",
      desc: "Hands-on workshop covering React.js and modern web technologies for APSIT students.",
    },
    {
      id: 4,
      college: "Indian Institute of Technology Bombay",
      title: "Techfest IIT Bombay",
      date: "2026-02-26",
      time: "10:00",
      location: "IIT Bombay Campus",
      desc: "Asia's largest science and technology festival with competitions, exhibitions, and talks.",
    },
    {
      id: 5,
      college: "Indian Institute of Technology Bombay",
      title: "AI & ML Research Symposium",
      date: "2026-01-25",
      time: "14:00",
      location: "Auditorium, IIT Bombay",
      desc: "Industry experts and researchers discussing latest trends in AI and Machine Learning.",
    },
    {
      id: 6,
      college: "NMIMS University",
      title: "Data Science Bootcamp",
      date: "2026-01-28",
      time: "09:00",
      location: "NMIMS Analytics Center",
      desc: "Intensive 3-day bootcamp on data analysis, visualization, and predictive modeling.",
    },
    {
      id: 7,
      college: "NMIMS University",
      title: "Business & Tech Fusion Summit",
      date: "2026-03-15",
      time: "10:00",
      location: "NMIMS Auditorium",
      desc: "Bridging business and technology - networking event with industry leaders.",
    },
    {
      id: 8,
      college: "All Colleges",
      title: "Inter-College Hackathon 2026",
      date: "2026-02-15",
      time: "10:00",
      location: "Multiple Venues",
      desc: "Open to all colleges - compete with the best tech minds across Mumbai.",
    },
    {
      id: 9,
      college: "All Colleges",
      title: "Cybersecurity Awareness Week",
      date: "2026-02-10",
      time: "11:00",
      location: "Online & Various Campuses",
      desc: "Learn about cyber threats, ethical hacking, and digital safety. Open to all students.",
    },
    {
      id: 10,
      college: "All Colleges",
      title: "Career Fair 2026",
      date: "2026-03-28",
      time: "10:00",
      location: "Convention Center",
      desc: "Meet recruiters from top tech companies and startups. All colleges welcome.",
    },
  ],
};
